resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

secret:
  name: default-token
  namespace: default

deployment:
  replicas: 1
  selector:
    matchLabels:
      app: gitapp
  template:
    metadata:
      labels:
        app: gitapp
    spec:
      containers:
        - name: gitapp
          image: $(Build.ArtifactStagingDirectory)/drop/gitapp:$(Build.BuildId)
          ports:
            - containerPort: 5500
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi

service:
  name: gitapp
  type: LoadBalancer
  ports:
    - port: 5500
      targetPort: 5500
  selector:
    app: gitapp
