apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitapp
  template:
    metadata:
      labels:
        app: gitapp
    spec:
      containers:
      - name: gitapp
        image: $(Build.ArtifactStagingDirectory)/drop/gitapp:$(Build.BuildId)
        ports:
        - containerPort: 5500
